version: '3.9'
services:
  database:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=soundcore
    ports:
      - "3306:3306"
    networks:
      - soundcore_dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database
    networks:
      - soundcore_dev

  meilisearch:
    image: getmeili/meilisearch
    restart: always
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=super_secret_master_key
    volumes:
      - ".docker/meilisearch:/meili_data"
    entrypoint: ["meilisearch", "--env=development"]
    networks:
      - soundcore_dev

networks:
  soundcore_dev: