name: Soundcore Image Build
      
on:
  push:
    branches:
      - 'main'

jobs:
  read_version:
    runs-on: ubuntu-latest
    outputs:
      packageVersion: ${{ steps.packageVersion.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Read version from package.json
        id: packageVersion
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: apps/api
          
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/soundcore:${{ needs.read_version.outputs.packageVersion }}
